name: Playwright Tests

on:
  schedule:
    - cron: '0 8 * * 1'  # every Monday at 08:00 UTC
  workflow_dispatch:  # Allows manual triggering
  
  push:
    branches:
      - main
  pull_request:


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1. Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Set up Node.js environment
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # 3. Install dependencies
    - name: Install dependencies
      run: npm ci

    # 4. Install Playwright dependencies (if needed)
    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    # 5. Run Playwright tests and display test list results
    - name: Run Playwright tests
      env:
        # BASE_URL: https://www.saucedemo.com
        BASE_URL: https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
      run: npx playwright test --reporter=html


    # 6. Upload test results (optional)
    - name: Upload Playwright test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: playwright-report/


