name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1. Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Set up Node.js environment
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # 3. Install dependencies
    - name: Install dependencies
      run: npm ci

    # 4. Install Playwright dependencies (if needed)
    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    # 5. Run Playwright tests
    - name: Run Playwright tests
      env:
        BASE_URL: https://www.saucedemo.com
      run: npx playwright test --reporter=list | sed -n 's/^\(.*\) › \(.*\) (\([0-9\.]*s\))$/\1 - \2 [\3] ✔/p' # or --reporter=html


    # 6. Upload test results (optional)
    - name: Upload Playwright test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: playwright-report/
